### PR TITLE
Leaderboard: Project Setup

### PR DESCRIPTION
**Pull request by aamir-asaram**
**In this PR I implemented the following:**
- Basic page layout
- Minimal styling to match the wireframe
- Dummy entries in the leaderboard to mimic the wireframe

### CODE REVIEW

**Review by AbelG101 — COMMENTED** [review]
# Hi @aamir-asaram 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that doesn't follow the proper Gitflow. That means you should create a new branch called `dev` or `development` and make that the main branch of this repo so that whenever you create a PR the merge request should be from `feature-branch` into `dev`. Please refer to this [article for more info](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by aamir-asaram** [comment]
Hey @AbelG101, I wasn't aware of that. Thanks for the feedback! :smile:

**Review by bobb-Rob — COMMENTED** [review]
Hi @aamir-asaram, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't follow the proper Gitflow. **_That means you should create a new branch called dev or development and make that the main branch of this repo_** so that whenever you create a PR the merge request should be from feature-branch into dev. Please refer to this [article for more info](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Olamarx — APPROVED** [review]
Hi @aamir-asaram, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- App folder structure ✔️
- Webpack setup ✔️
- Gitflow ✔️

## Optional suggestions
- [OPTIONAL] I will encourage you to add `.gitIgnore` file and add all files to be ignored such as the node_modules so that it would not push it to gitHub, you won't like the experience if you push node_module to your repo, moreso, it is unprofessional.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aamir-asaram** [comment]
Hey @Olamarx, I had a .gitignore file set up but I forgot to include it in my push. Thanks a lot for pointing that out! :smile:

**Pull request closed without merging**
